all: prog

prog: main.o matrix.o jordan.o
	g++ main.o matrix.o jordan.o -o proga



main.o: main.cpp matrix.hpp jordan.hpp
	g++ -g -Wall -Wextra -Werror -pedantic -std=gnu++0x -O3 -c main.cpp

matrix.o: matrix.cpp matrix.hpp
	g++ -g -Wall -Wextra -Werror -pedantic -std=gnu++0x -O3 -c matrix.cpp

jord.o: jord.cpp jordan.hpp
	g++ -g -Wall -Wextra -Werror -pedantic -std=gnu++0x -O3 -c jordan.cpp


clean:
	rm -f *.o prog
